# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"  # except markdown
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements

  # Python
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
  - repo: https://github.com/google/yapf
    rev: v0.31.0
    hooks:
      - id: yapf
        args:
          - "-i"  # auto fix
          - "-p"  # parallel run
  - repo: https://github.com/pycqa/pylint
    rev: v2.9.3
    hooks:
      - id: pylint
